services:
  everave.server:
    image: ${DOCKER_REGISTRY-}everaveserver
    build:
      context: .
      dockerfile: everave.server/Dockerfile
    ports:
      - "5000:80"
    depends_on:
      - imagehandler
      - elasticsearch
    environment:
      - UseAzureBlobStorage=false
      - MongoDbConnectionString=mongodb://mongodb:27017
      - UseAzureDeployment=true
      - UseElasticSearch=true
      - ElasticSearchUrl=http://elasticsearch:9200

  imagehandler:
    image: imagehandler
    build:
      context: .
      dockerfile: ImageService/Dockerfile
    volumes:
      - image-storage:/app/images 

  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    volumes:
      - mongodb_data:/data/db

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:9.0.1
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false  # disable security for local dev
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ulimits:
      memlock:
        soft: -1
        hard: -1

volumes:
  image-storage:
  mongodb_data: