name: Deploy to ACR as Staging and create a new slot

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/everaveserver:staging --file everave.server/Dockerfile .

      - name: Push Docker image
        run: |
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/everaveserver:staging
    
      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Create a new slot
        run: |
          az webapp deployment slot create \
            --name ${{ secrets.AZURE_APP_SERVICE_NAME }} \
            --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
            --slot staging-test

      - name: Deploy image to the new slot
        run: |
          az webapp config container set \
            --name ${{ secrets.AZURE_APP_SERVICE_NAME }} \
            --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
            --slot staging-test \
            --container-image-name ${{ secrets.ACR_LOGIN_SERVER }}/everaveserver:staging \
            --container-registry-url https://${{ secrets.ACR_LOGIN_SERVER }} \
            --container-registry-user ${{ secrets.ACR_USERNAME }} \
            --container-registry-password ${{ secrets.ACR_PASSWORD }}

      - name: Copy environment variables from main app to slot
        run: |
          MAIN_APP_SETTINGS=$(az webapp config appsettings list \
            --name ${{ secrets.AZURE_APP_SERVICE_NAME }} \
            --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
            --query "[].{name:name, value:value}" -o json)

          echo $MAIN_APP_SETTINGS | jq -c '.[]' | while read i; do
            KEY=$(echo $i | jq -r '.name')
            VALUE=$(echo $i | jq -r '.value')
            az webapp config appsettings set \
              --name ${{ secrets.AZURE_APP_SERVICE_NAME }} \
              --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
              --slot staging-test \
              --settings $KEY=$VALUE
          done